cc_library(
    name = "char_streams_adapters",
    srcs = [
        "char_aligned_bit_reader.cc",
        "char_aligned_bit_writer.cc",
    ],
    hdrs = [
        "char_aligned_bit_reader.h",
        "char_aligned_bit_writer.h",
    ],
    deps = [
        "//bits_manipulation:bits_manipulation",
        "//encryption/bit_io:bit_io",
    ],
    visibility = ["//visibility:public"],
)
