cc_library(
    name = "string_io",
    srcs = [
        "string_byte_reader.cc",
        "string_bit_writer.cc",
    ],
    hdrs = [
        "string_byte_reader.h",
        "string_bit_writer.h",
    ],
    deps = [
        "//bits_manipulation:bits_manipulation",
        "//encryption:huffman_encryption"
    ],
    visibility = ["//visibility:public"],
)
