cc_library(
    name = "string_io",
    srcs = [
        "string_byte_reader.cc",
    ],
    hdrs = [
        "string_byte_reader.h",
    ],
    deps = [
        "//encryption:huffman_encryption"
    ],
    visibility = ["//visibility:public"],
)
