image:
  - Ubuntu2004

install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel_3.7.1-linux-x86_64.deb
  - sudo dpkg -i bazel_3.7.1-linux-x86_64.deb
  - sudo apt install -y g++-10
  - sudo apt install -y gcc-10
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
build_script:
- echo Ubuntu build script
- bazel test //test:unittest

