image:
  - Ubuntu2004

install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel_3.7.1-linux-x86_64.deb
  - sudo dpkg -i bazel_3.7.1-linux-x86_64.deb
  - sudo apt install -y g++-10
  - sudo apt install -y gcc-10
build_script:
- echo Ubuntu build script
- export CC=/usr/bin/gcc-10
- export CXX=/usr/bin/g++-10
- bazel test //test:unittest
- bazel test //test:unittest --config=asan
- bazel test //test:unittest --config=ubsan

