image:
  - Ubuntu1804

install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.7.1/bazel_3.7.1-linux-x86_64.deb
  - sudo dpkg -i bazel_3.7.1-linux-x86_64.deb
build_script:
- echo Ubuntu build script
- cd src
- bazel test //test:unittest

