cc_library(
    name = "huffman_encryption",
    srcs = [
        "huffman_encryption.cc",
    ],
    hdrs = [
        "byte_reader.h",
        "byte_writer.h",
        "huffman_encryption.h",
    ],
    deps = [
        "//encryption/huffman_tree:huffman_tree",
    ],
    visibility = ["//visibility:public"],
)
