cc_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    deps = [
        "//third_party/CLI11:CLI11",
        "//encryption:huffman_encryption",
    ],
    visibility = ["//visibility:public"],
)
