cc_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    deps = [
        "//third_party/CLI11:CLI11",
        "//letter:letter",
        "//letter/single_byte_letter:single_byte_letter",
        "//encoding:huffman_encoding",
    ],
    visibility = ["//visibility:public"],
)
