cc_library(
    name = "byte_streams_adapters",
    srcs = [
        "byte_aligned_bit_reader.cc",
        "byte_aligned_bit_writer.cc",
    ],
    hdrs = [
        "byte_aligned_bit_reader.h",
        "byte_aligned_bit_writer.h",
    ],
    deps = [
        "//bits_manipulation:bits_manipulation",
        "//bit_io:bit_io",
    ],
    visibility = ["//visibility:public"],
)
