cc_library(
    name = "huffman_tree",
    srcs = [
        "huffman_tree_builder.cc",
        "text_splitter.cc",
    ],
    hdrs = [
        "huffman_tree_builder.h",
        "text_splitter.h",
    ],
    deps = [
        "//bits_manipulation:bits_manipulation",
    ],
    visibility = [
        "//encryption:__pkg__",
        "//test:__pkg__",
    ],
)
