cc_library(
    name = "bit_io",
    srcs = [
        "bit_reader.cc",
        "bit_writer.cc",
    ],
    hdrs = [
        "bit_reader.h",
        "bit_writer.h",
    ],
    deps = [
        "//bits_manipulation:bits_manipulation",
    ],
    visibility = ["//visibility:public"],
)
