py_binary(
    name = "benchmark",
    srcs = ["benchmark.py"],
    data = [
        "//main:main",
        "//perf_tests:example.cc",
        "//perf_tests:sample_alphabet.txt",
        "//perf_tests:war_and_peace.txt",
    ],
)
