cc_library(
    name = "text_splitter",
    srcs = [
        "text_splitter.cc",
        "trie.cc",
    ],
    hdrs = [
        "text_splitter.h",
        "trie.h",
    ],
    visibility = [
        "//encryption:__pkg__",
        "//test:__pkg__",
    ],
)
