cc_library(
    name = "letter",
    hdrs = [
        "letter.h",
    ],
    deps = [
        "//bit_io:bit_io",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "one_byte_letter",
    hdrs = [
        "one_byte_letter.h",
    ],
    deps = [
        "//letter:letter",
    ],
    visibility = ["//visibility:public"],
)
