cc_library(
    name = "letter",
    hdrs = [
        "letter.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "one_byte_letter",
    hdrs = [
        "one_byte_letter.h",
    ],
    visibility = ["//visibility:public"],
)
