cc_library(
    name = "letter",
    hdrs = [
        "letter.h",
    ],
    visibility = [
        "//encryption:__pkg__",
        "//test:__pkg__",
    ],
)

cc_library(
    name = "one_byte_letter",
    hdrs = [
        "one_byte_letter.h",
    ],
    visibility = [
        "//encryption:__pkg__",
        "//test:__pkg__",
    ],
)
