cc_library(
    name = "fixed_alphabet_letter",
    hdrs = [
        "fixed_alphabet_letter.h",
    ],
    deps = [
        "//letter:letter",
        "//letter/fixed_alphabet_letter/trie:trie",
    ],
    visibility = ["//visibility:public"],
)