cc_library(
    name = "fixed_alphabet_letter",
    hdrs = [
        "fixed_alphabet_letter.h",
    ],
    deps = [
        "//letter:letter",
        "//letter/fixed_alphabet_letter:trie",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "trie",
    hdrs = [
        "trie.h",
    ],
    srcs = [
        "trie.cc",
    ],
    visibility = ["//visibility:public"],
)