cc_library(
    name = "char_streams_adapters",
    srcs = [
        "char_istream_adapter.cc",
        "char_ostream_adapter.cc",
    ],
    hdrs = [
        "char_istream_adapter.h",
        "char_ostream_adapter.h",
    ],
    deps = [
        "//bits_manipulation:bits_manipulation",
        "//encryption:huffman_encryption",
    ],
    visibility = ["//visibility:public"],
)
