cc_library(
    name = "huffman_encoding",
    hdrs = [
        "huffman_encoding.h",
    ],
    deps = [
        "//letter:letter",
        "//bit_io:bit_io",
        "//encoding/char_streams_adapters:char_streams_adapters",
        "//encoding/huffman_tree:huffman_tree",
        "//encoding/text_splitter:text_splitter",
    ],
    visibility = ["//visibility:public"],
)
